<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE curso[
<!ELEMENT curso (asignatura+)>
<!ELEMENT asignatura (alumnos?,profesor?)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, apellidos)>
<!ELEMENT profesor (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
]>
<curso>
    <asignatura>
        <alumnos>
            <alumno>
                <nombre></nombre>
                <apellidos></apellidos>
            </alumno>
            <alumno>
                <nombre></nombre>
                <apellidos></apellidos>
            </alumno>
            <alumno>
                <nombre></nombre>
                <apellidos></apellidos>
            </alumno>
        </alumnos>
        <profesor>
            <nombre></nombre>
            <apellidos></apellidos>
        </profesor>
    </asignatura>
    <asignatura>
        <profesor>
            <nombre></nombre>
            <apellidos></apellidos>
        </profesor>
    </asignatura>
</curso>