=== DavidRG4/Lenguaje-de-marcas/U1-Introduccion_XML/Xml/biblioteca.dtd
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (autor, titulo, genero, capitulos?)>
<!ELEMENT autor (nombre, apellidos)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT capitulos (capitulo+)>
<!ELEMENT capitulo (nombre, inicio, final)>
<!ELEMENT inicio (#PCDATA)>
<!ELEMENT final (#PCDATA)>

=== DavidRG4/Lenguaje-de-marcas/U1-Introduccion_XML/Xml/biblioteca.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE biblioteca SYSTEM "biblioteca.dtd">
<biblioteca>
    <libro>
        <autor>
            <nombre></nombre>
            <apellidos></apellidos>
        </autor>
        <titulo></titulo>
        <genero></genero>
        <capitulos>
            <capitulo>
                <nombre></nombre>
                <inicio></inicio>
                <final></final>
            </capitulo>
            <capitulo>
                <nombre></nombre>
                <inicio></inicio>
                <final></final>
            </capitulo>
        </capitulos>
    </libro>
</biblioteca>
