=== DavidRG4/Lenguaje-de-marcas/U1-Introduccion_XML/Xml/netflix.dtd
<!ELEMENT netflix (serie)>
<!ELEMENT serie (nombre, director, capitulo+)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT director (nombre, apellidos)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT capitulo (temporada?, numero, orden)>
<!ELEMENT temporada (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT orden (#PCDATA)>

=== DavidRG4/Lenguaje-de-marcas/U1-Introduccion_XML/Xml/netflix.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE netflix SYSTEM "netflix.dtd">
<netflix>
    <serie>
        <nombre></nombre>
        <director><nombre></nombre><apellidos></apellidos></director>
        <capitulo>
            <temporada></temporada>
            <numero></numero>
            <orden></orden>
        </capitulo>
    </serie>

</netflix>
